### ISSUE TITLE
Validation issue in ratner stock

### ISSUE THREAD

**Issue by AnandShegde** [alan-turing-institute/TCPD#16]
I am getting the following error while downloading the data sets
```Running collect action for dataset: ratner_stock ... Traceback (most recent call last):
  File "/home/anand/dirichlet/TCPD/build_tcpd.py", line 115, in <module>
    main()
  File "/home/anand/dirichlet/TCPD/build_tcpd.py", line 110, in main
    func(name, script)
  File "/home/anand/dirichlet/TCPD/build_tcpd.py", line 85, in collect_dataset
    return run_dataset_func(name, script, "collect")
  File "/home/anand/dirichlet/TCPD/build_tcpd.py", line 81, in run_dataset_func
    func(output_dir=dir_path)
  File "./datasets/ratner_stock/get_ratner_stock.py", line 170, in collect
    write_patch(json_path, target_path=json_path)
  File "./datasets/ratner_stock/get_ratner_stock.py", line 65, in wrapper
    raise ValidationError(target)
tcpd.ratner_stock.ValidationError: ./datasets/ratner_stock/ratner_stock.json
```
Please see the downloaded dataset [here](https://drive.google.com/file/d/1jmlPgvn0gVTlaXkj_dQEnLSM_VJG5VNC/view?usp=sharing)

I am also facing issue #3

**Comment by GjjvdBurg** [comment]
Fix released, please try again
